### ISSUE TITLE
Client doesn't remain in changed remote directory

### ISSUE THREAD

**Issue by bburke4** [webpod/webpod#1]
Hi, is changing the current working directory on the remote host supposed to work? I can change directories and run a command as a single command, but it doesn't remain in the directory on subsequent commands.

```JavaScript
#!/usr/bin/env zx
import 'zx/globals';
import { ssh } from 'zx';

const $ssh = await ssh('myhost', { JumpHost: 'myjumphost' });

console.log('initial dir: ', (await $ssh`pwd`).stdout);
console.log('change dir and pwd:', (await $ssh`cd /mnt/app && pwd `).stdout);
console.log('pwd again:', (await $ssh`pwd`).stdout);
console.log('change dir:', (await $ssh`cd /mnt/app`).stdout);
console.log('pwd:', (await $ssh`pwd`).stdout);

```

Here is the output:
```
initial dir:  /home/bburke

change dir and pwd: /mnt/app

pwd again: /home/bburke

change dir: 
pwd: /home/bburke
```

Am I doing something wrong? Is this expected? Any suggested workaround? Thank you :)

**Comment by antonmedv** [comment]
This is intentional.

Every command is executed in its own session. But still in a single TCP connection.

Consider the following example: 

```js
await $`cd /some/dir`
// internet breaks down
await $`run-cmd` 
```

The `run-cmd` command will fail. Or if automatically reconnected, the command will be executed in the wrong dir.

I can add a method like this:

```js
$.cd('/some/dir')
await $`run-cmd` // will be prefixed by `cd /some/dir && `
