### ISSUE TITLE
Can't access to web page

### ISSUE THREAD

**Issue by sh-cho** [webpod/webpod#2]
<img width="923" alt="image" src="https://user-images.githubusercontent.com/11611397/226091069-ef932760-1de1-47da-9223-ede4293a0383.png">

I cannot access webpod.dev because chrome says certificate is invalid.

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/11611397/226091059-8d9ae19f-a26f-4e19-b079-1ecfc11ab5be.png">

maybe dns propagation is not completed in Korea?

**Comment by antonmedv** [comment]
I still in development of the website) will update next week

**Comment by ELLIOTTCABLE** [comment]
This is also more problematic due to the lack of any description in the README. What _is_ this? 😅

**Comment by antonmedv** [comment]
Fixed. First version of website is available.
